#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_LOCAL_FILE="${SKILL_DIR}/.env.local"
MCP_DOC_URL="https://github.com/xpzouying/xiaohongshu-mcp"

load_env_file() {
  local file="$1"
  if [[ -f "${file}" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "${file}"
    set +a
  fi
}

# Reuse existing values if .env.local already exists.
load_env_file "${ENV_LOCAL_FILE}"

MCP_PATH_ARG="${XHS_MCP_BINARY_PATH:-}"
WEBHOOK_ARG="${FEISHU_WEBHOOK_URL:-}"
APP_ID_ARG="${FEISHU_APP_ID:-}"
APP_SECRET_ARG="${FEISHU_APP_SECRET:-}"
NON_INTERACTIVE=0

is_mcp_like_binary_name() {
  local bin_path="$1"
  local base_name
  base_name="$(basename "${bin_path}")"
  [[ "${base_name}" == xiaohongshu-mcp* ]]
}

validate_mcp_path_or_die() {
  local candidate="$1"
  if [[ -z "${candidate}" ]]; then
    return 0
  fi
  if [[ ! -x "${candidate}" ]]; then
    echo "Provided --mcp-path is not executable: ${candidate}" >&2
    exit 2
  fi
  if ! is_mcp_like_binary_name "${candidate}" && [[ "${XHS_SKIP_MCP_NAME_CHECK:-0}" != "1" ]]; then
    echo "Provided --mcp-path does not look like xiaohongshu-mcp: ${candidate}" >&2
    echo "If this is intentional, set XHS_SKIP_MCP_NAME_CHECK=1 and retry." >&2
    exit 2
  fi
}

usage() {
  cat <<'USAGE'
Usage: bash scripts/install.sh [options]

Options:
  --mcp-path <path>           Set XHS_MCP_BINARY_PATH (optional)
  --feishu-webhook <url>      Set FEISHU_WEBHOOK_URL (optional)
  --feishu-app-id <id>        Set FEISHU_APP_ID (optional)
  --feishu-app-secret <sec>   Set FEISHU_APP_SECRET (optional)
  --non-interactive           Do not prompt
  -h, --help                  Show help
USAGE
}

prompt() {
  local message="$1"
  local default="${2:-}"
  local value=""
  if [[ ${NON_INTERACTIVE} -eq 1 ]]; then
    printf '%s\n' "${default}"
    return
  fi
  if [[ -n "${default}" ]]; then
    read -r -p "${message} [${default}]: " value || true
    [[ -z "${value}" ]] && value="${default}"
  else
    read -r -p "${message}: " value || true
  fi
  printf '%s\n' "${value}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mcp-path)
      if [[ $# -lt 2 || -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "Missing value for --mcp-path" >&2
        exit 2
      fi
      MCP_PATH_ARG="${2:-}"
      shift 2
      ;;
    --feishu-webhook)
      if [[ $# -lt 2 || -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "Missing value for --feishu-webhook" >&2
        exit 2
      fi
      WEBHOOK_ARG="${2:-}"
      shift 2
      ;;
    --feishu-app-id)
      if [[ $# -lt 2 || -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "Missing value for --feishu-app-id" >&2
        exit 2
      fi
      APP_ID_ARG="${2:-}"
      shift 2
      ;;
    --feishu-app-secret)
      if [[ $# -lt 2 || -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "Missing value for --feishu-app-secret" >&2
        exit 2
      fi
      APP_SECRET_ARG="${2:-}"
      shift 2
      ;;
    --non-interactive)
      NON_INTERACTIVE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 2
      ;;
  esac
done

validate_mcp_path_or_die "${MCP_PATH_ARG}"

if [[ ${NON_INTERACTIVE} -eq 0 ]]; then
  if [[ -z "${MCP_PATH_ARG}" ]]; then
    MCP_PATH_ARG="$(prompt "XHS MCP 可执行文件路径（可选；留空表示使用 PATH）")"
  fi
  validate_mcp_path_or_die "${MCP_PATH_ARG}"

  if [[ -z "${WEBHOOK_ARG}" ]]; then
    WEBHOOK_ARG="$(prompt "Feishu webhook URL（可选）")"
  fi
  if [[ -n "${WEBHOOK_ARG}" ]]; then
    if [[ -z "${APP_ID_ARG}" ]]; then
      APP_ID_ARG="$(prompt "Feishu APP ID（可选）")"
    fi
    if [[ -z "${APP_SECRET_ARG}" ]]; then
      APP_SECRET_ARG="$(prompt "Feishu APP SECRET（可选）")"
    fi
  fi
fi

mkdir -p "${SKILL_DIR}"
: > "${ENV_LOCAL_FILE}"
{
  echo "# Generated by scripts/install.sh"
  echo "# This file only stores local runtime config."
  echo "# MCP binary is NOT auto-installed by this skill."
} >> "${ENV_LOCAL_FILE}"

write_env_kv() {
  local key="$1"
  local value="$2"
  printf '%s=%q\n' "${key}" "${value}" >> "${ENV_LOCAL_FILE}"
}

write_env_kv "WORKFLOW_DIR" "${SKILL_DIR}"
write_env_kv "XHS_MCP_BINARY_PATH" "${MCP_PATH_ARG}"
write_env_kv "FEISHU_WEBHOOK_URL" "${WEBHOOK_ARG}"
write_env_kv "FEISHU_WEBHOOK_TIMEOUT" "15"
write_env_kv "FEISHU_APP_ID" "${APP_ID_ARG}"
write_env_kv "FEISHU_APP_SECRET" "${APP_SECRET_ARG}"
write_env_kv "XHS_AUTO_LOGIN_FEISHU" "1"
write_env_kv "XHS_LOGIN_WAIT_SECONDS" "420"
write_env_kv "XHS_LOGIN_POLL_SECONDS" "25"
write_env_kv "XHS_LOGIN_QR_REFRESH_SECONDS" "210"
write_env_kv "XHS_RESET_COOKIES_BEFORE_QR" "0"
write_env_kv "XHS_ENFORCE_HEADLESS_TRUE" "1"
write_env_kv "XHS_MCP_HEADLESS" "true"
write_env_kv "JOB_TOPIC" ""
write_env_kv "JOB_REGION" ""
write_env_kv "JOB_TIME_CONSTRAINT" ""
write_env_kv "JOB_OUTPUT_FORMAT" ""
write_env_kv "XHS_REQUIREMENT_GUARD" "1"

echo "Wrote config: ${ENV_LOCAL_FILE}"

resolved_mcp=""
if [[ -n "${MCP_PATH_ARG}" && -x "${MCP_PATH_ARG}" ]]; then
  resolved_mcp="${MCP_PATH_ARG}"
elif command -v xiaohongshu-mcp >/dev/null 2>&1; then
  resolved_mcp="$(command -v xiaohongshu-mcp)"
fi

echo
if [[ -n "${resolved_mcp}" ]] && (is_mcp_like_binary_name "${resolved_mcp}" || [[ "${XHS_SKIP_MCP_NAME_CHECK:-0}" == "1" ]]); then
  echo "MCP preflight: OK (${resolved_mcp})"
else
  echo "MCP preflight: NOT FOUND"
  echo "请先安装 xiaohongshu-mcp，并满足其一："
  echo "  1) 配置环境变量 XHS_MCP_BINARY_PATH=/abs/path/to/xiaohongshu-mcp"
  echo "  2) 将 xiaohongshu-mcp 加入 PATH"
  echo "安装文档：${MCP_DOC_URL}"
fi

echo
echo "Next commands:"
echo "  bash ${SKILL_DIR}/scripts/xhs_skill.sh clarify"
echo "  bash ${SKILL_DIR}/scripts/xhs_skill.sh all --topic 'AI 工具' --time-constraint '近7天' --output-format both --region '上海' --config configs/job_fetch.profile.example.json"
